1.4.0 release
sendsmaily/smaily-prestashop-module pull request #19
Opened 2020-08-13 14:34 UTC by TomAbel

2020-08-24 13:52 UTC, sinukaarel commented
@TomAbel you can now [copy the PR template](https://github.com/sendsmaily/smaily-prestashop-module/blob/master/.github/pull_request_template.md) and try how that works in practice.

2020-08-25 15:38 UTC, TomAbel commented
I didn't know what to include in the userguide about RSS. Is there an available guide about RSS in Smaily helpdesk or are the help-block elements sufficient for help?

2020-08-26 05:53 UTC, kaittodesk commented
I don't think we have an article in the Smaily knowledge base about RSS.

If you could just add a screenshot, description about the feature (what user can do with it), and possible limitations to the user guide, then I think it will suffice.

2020-08-27 06:01 UTC, kaittodesk requested changes

2020-08-27 12:01 UTC, kaittodesk approved these changes

2020-08-27 12:02 UTC, merged